export const SHOW_DEPOSIT_MODAL = 'SHOW_DEPOSIT_MODAL';
export const HIDE_DEPOSIT_MODAL = 'HIDE_DEPOSIT_MODAL';

export const SHOW_WITHDRAW_MODAL = 'SHOW_WITHDRAW_MODAL';
export const HIDE_WITHDRAW_MODAL = 'HIDE_WITHDRAW_MODAL';

export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';

export const SET_TOKEN_BALANCE = 'SET_TOKEN_BALANCE';
export const SET_TOKEN_USD_BALANCE = 'SET_TOKEN_USD_BALANCE';
export const SET_WITHDRAWABLE_BALANCE = 'SET_WITHDRAWABLE_BALANCE';
export const SET_USERDATA = 'SET_USERDATA';
export const SET_USED_REFCODE = 'SET_USED_REFCODE';
export const INIT_USER_DATA = 'INIT_USER_DATA';
export const SET_WALLET_ADDRESS = 'SET_WALLET_ADDRESS';

export const SET_LOADING_DEPOSIT = 'SET_LOADING_DEPOSIT';
export const SET_LOADING_WITHDRAW = 'SET_LOADING_WITHDRAW';